package View;

import Model.Meja;
import Model.Menu;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionListener;

public class FrameRestoran extends javax.swing.JFrame {
    
    public FrameRestoran() {
        initComponents();
        btn_hapus.setEnabled(false);
    }
    
    public String getLoginNama() {return tf_nama.getText();}
    public void setLoginNama(String s) {tf_nama.setText(s);}
    public String getLoginPass() {return String.copyValueOf(tf_password.getPassword());}
    public void setLoginPassEmpty() {tf_password.setText("");}
    public String getOrder() {return String.valueOf(cb_menu.getSelectedItem());}
    public int getQty() {return (int) spn_jlhMakanan.getValue();}
    public int getNoMejaPemesanan() {return Integer.parseInt((String)(cb_noMeja_pemesanan.getSelectedItem()));}
    public int getIndexListPemesanan() {return list_pemesanan.getSelectedIndex();}
    public int getMejaReady() {return list_siapAntar.getSelectedIndex();}
    public int getMejaReadyPay() {return Integer.parseInt((String)cb_noMeja_pembayaran.getSelectedItem());}
    public int getMejaKoki() {return Integer.parseInt(list_noMeja_koki.getSelectedValue());}
    public String getPesananKoki() {return list_otwMasak.getSelectedValue();}
    public void setMenuPopuler(String s) {isiMenuPopuler.setText(s);}
    public void setOmzet(int omzet) {isiOmzet.setText(Integer.toString(omzet));}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laporanResto = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_menuPopuler = new javax.swing.JLabel();
        lbl_omzet = new javax.swing.JLabel();
        isiMenuPopuler = new javax.swing.JLabel();
        isiOmzet = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loginGagal = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lbl_noMeja_pemesanan = new javax.swing.JLabel();
        cb_noMeja_pemesanan = new javax.swing.JComboBox<>();
        lbl_Menu = new javax.swing.JLabel();
        lbl_jlhMakanan = new javax.swing.JLabel();
        cb_menu = new javax.swing.JComboBox<>();
        spn_jlhMakanan = new javax.swing.JSpinner();
        btn_tambah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_pemesanan = new javax.swing.JList<>();
        btn_hapus = new javax.swing.JButton();
        btn_pesan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_konfirmasi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_noMeja_koki = new javax.swing.JList<>();
        lbl_noMeja_koki = new javax.swing.JLabel();
        lbl_pesananMeja_koki = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        list_otwMasak = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_siapAntar = new javax.swing.JList<>();
        btn_antar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lbl_noMeja_pembayaran = new javax.swing.JLabel();
        cb_noMeja_pembayaran = new javax.swing.JComboBox<>();
        lbl_totalHarga = new javax.swing.JLabel();
        tf_totalHarga = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        list_pembayaran = new javax.swing.JList<>();
        btn_bayar = new javax.swing.JButton();
        lbl_rp = new javax.swing.JLabel();
        btn_Hitung = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lbl_nama = new javax.swing.JLabel();
        tf_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        lbl_pass = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("LAPORAN RESTORAN BULAN INI");
        jLabel1.setToolTipText("");

        lbl_menuPopuler.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbl_menuPopuler.setText("Menu Populer");

        lbl_omzet.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbl_omzet.setText("Omzet");

        isiMenuPopuler.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N

        isiOmzet.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        jLabel4.setText("Rp.");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbl_menuPopuler)
                        .addGap(69, 69, 69)
                        .addComponent(isiMenuPopuler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbl_omzet)
                        .addGap(132, 132, 132)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isiOmzet, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(82, 82, 82)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(isiMenuPopuler, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_menuPopuler))
                .addGap(60, 60, 60)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_omzet)
                        .addComponent(jLabel4))
                    .addComponent(isiOmzet, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout laporanRestoLayout = new javax.swing.GroupLayout(laporanResto.getContentPane());
        laporanResto.getContentPane().setLayout(laporanRestoLayout);
        laporanRestoLayout.setHorizontalGroup(
            laporanRestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanRestoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        laporanRestoLayout.setVerticalGroup(
            laporanRestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanRestoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nama/password");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("salah atau kosong.");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel2.getAccessibleContext().setAccessibleName("Nama/password salah\nzzzzzzzzzzzzzzzzzzz");

        javax.swing.GroupLayout loginGagalLayout = new javax.swing.GroupLayout(loginGagal.getContentPane());
        loginGagal.getContentPane().setLayout(loginGagalLayout);
        loginGagalLayout.setHorizontalGroup(
            loginGagalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginGagalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        loginGagalLayout.setVerticalGroup(
            loginGagalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginGagalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbedPane.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lbl_noMeja_pemesanan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_noMeja_pemesanan.setText("No. Meja");

        cb_noMeja_pemesanan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cb_noMeja_pemesanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        lbl_Menu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_Menu.setText("Menu");

        lbl_jlhMakanan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_jlhMakanan.setText("Jumlah");

        cb_menu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cb_menu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        spn_jlhMakanan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        spn_jlhMakanan.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btn_tambah.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_tambah.setText("Tambah");

        list_pemesanan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        list_pemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_pemesananMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(list_pemesanan);

        btn_hapus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_hapus.setText("Hapus");

        btn_pesan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_pesan.setText("Pesan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(btn_tambah)
                .addGap(306, 306, 306)
                .addComponent(btn_hapus)
                .addGap(51, 51, 51)
                .addComponent(btn_pesan)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_Menu)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_jlhMakanan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                                .addComponent(spn_jlhMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cb_noMeja_pemesanan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_noMeja_pemesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cb_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lbl_noMeja_pemesanan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_noMeja_pemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(lbl_Menu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_jlhMakanan)
                            .addComponent(spn_jlhMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_tambah)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_pesan)
                        .addComponent(btn_hapus)))
                .addGap(46, 46, 46))
        );

        TabbedPane.addTab("Pemesanan", jPanel2);

        btn_konfirmasi.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        btn_konfirmasi.setText("Konfirmasi");

        list_noMeja_koki.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        list_noMeja_koki.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_noMeja_koki);

        lbl_noMeja_koki.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_noMeja_koki.setText("Nomor Meja");

        lbl_pesananMeja_koki.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_pesananMeja_koki.setText("List Pesanan");

        list_otwMasak.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        list_otwMasak.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(list_otwMasak);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_noMeja_koki)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_pesananMeja_koki)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(btn_konfirmasi)
                        .addGap(130, 130, 130))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(btn_konfirmasi)
                .addContainerGap(238, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_noMeja_koki)
                    .addComponent(lbl_pesananMeja_koki))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        TabbedPane.addTab("Menu Koki", jPanel3);

        list_siapAntar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jScrollPane3.setViewportView(list_siapAntar);

        btn_antar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_antar.setText("Antar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                .addComponent(btn_antar)
                .addGap(196, 196, 196))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(btn_antar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Antar Pesanan", jPanel4);

        lbl_noMeja_pembayaran.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_noMeja_pembayaran.setText("No. Meja");

        cb_noMeja_pembayaran.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cb_noMeja_pembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        lbl_totalHarga.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_totalHarga.setText("Total Harga");

        tf_totalHarga.setEditable(false);
        tf_totalHarga.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        list_pembayaran.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jScrollPane4.setViewportView(list_pembayaran);

        btn_bayar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_bayar.setText("Bayar");

        lbl_rp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_rp.setText("Rp.");

        btn_Hitung.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_Hitung.setText("Hitung");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_noMeja_pembayaran)
                    .addComponent(lbl_totalHarga))
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbl_rp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_totalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cb_noMeja_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Hitung)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_bayar)
                .addGap(156, 156, 156))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_noMeja_pembayaran)
                    .addComponent(cb_noMeja_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Hitung))
                .addGap(118, 118, 118)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_totalHarga)
                    .addComponent(tf_totalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_rp))
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane4)
                .addGap(18, 18, 18)
                .addComponent(btn_bayar)
                .addContainerGap())
        );

        TabbedPane.addTab("Pembayaran", jPanel5);

        lbl_nama.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_nama.setText("Nama");

        tf_password.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btn_login.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_login.setText("Log in");

        lbl_pass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_pass.setText("Password");

        tf_nama.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(lbl_nama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addComponent(tf_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_login)
                            .addComponent(tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(229, 229, 229))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(213, 213, 213)
                    .addComponent(lbl_pass)
                    .addContainerGap(633, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nama)
                    .addComponent(tf_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btn_login)
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(218, 218, 218)
                    .addComponent(lbl_pass)
                    .addContainerGap(243, Short.MAX_VALUE)))
        );

        TabbedPane.addTab("Laporan", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void list_pemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_pemesananMouseClicked
        if (evt.getClickCount()==1) {
            btn_hapus.setEnabled(true);
        }
    }//GEN-LAST:event_list_pemesananMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRestoran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton btn_Hitung;
    private javax.swing.JButton btn_antar;
    private javax.swing.JButton btn_bayar;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_konfirmasi;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_pesan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> cb_menu;
    private javax.swing.JComboBox<String> cb_noMeja_pembayaran;
    private javax.swing.JComboBox<String> cb_noMeja_pemesanan;
    private javax.swing.JLabel isiMenuPopuler;
    private javax.swing.JLabel isiOmzet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JDialog laporanResto;
    private javax.swing.JLabel lbl_Menu;
    private javax.swing.JLabel lbl_jlhMakanan;
    private javax.swing.JLabel lbl_menuPopuler;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_noMeja_koki;
    private javax.swing.JLabel lbl_noMeja_pembayaran;
    private javax.swing.JLabel lbl_noMeja_pemesanan;
    private javax.swing.JLabel lbl_omzet;
    private javax.swing.JLabel lbl_pass;
    private javax.swing.JLabel lbl_pesananMeja_koki;
    private javax.swing.JLabel lbl_rp;
    private javax.swing.JLabel lbl_totalHarga;
    private javax.swing.JList<String> list_noMeja_koki;
    private javax.swing.JList<String> list_otwMasak;
    private javax.swing.JList<String> list_pembayaran;
    private javax.swing.JList<String> list_pemesanan;
    private javax.swing.JList<String> list_siapAntar;
    private javax.swing.JDialog loginGagal;
    private javax.swing.JSpinner spn_jlhMakanan;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JTextField tf_totalHarga;
    // End of variables declaration//GEN-END:variables

    public void loadMenu(List<Menu> menus) {
        cb_menu.removeAllItems();
        for (Menu m: menus) {
            cb_menu.addItem(m.getNama());
        }
    }
    
    public void loadMejaPemesanan(List<Meja> tables) {
        cb_noMeja_pemesanan.removeAllItems();
        for (Meja mj: tables) {
            if(!mj.isIsi()) {
                cb_noMeja_pemesanan.addItem(Integer.toString(mj.getNomor()));
            }
        }
    }
    
    public void loadSiapAntar(List<Integer> ready) {
        DefaultListModel<String> listReady = new DefaultListModel<>();
        for(Integer r: ready) {
            listReady.addElement(Integer.toString(r));
        }
        list_siapAntar.setModel(listReady);
    }
    
    public void loadMejaSiapBayar(List<Integer> mejaSiapBayar) {
        cb_noMeja_pembayaran.removeAllItems();
        for (Integer mj: mejaSiapBayar) {
            cb_noMeja_pembayaran.addItem(Integer.toString(mj));
        }
    }
    
    public void loadTotalHarga(int harga) {
        tf_totalHarga.setText(Integer.toString(harga));
    }
    
    public void addButtonListener (ActionListener buttonListener) {
        btn_tambah.addActionListener(buttonListener);
        btn_hapus.addActionListener(buttonListener);
        btn_pesan.addActionListener(buttonListener);
        btn_konfirmasi.addActionListener(buttonListener);
        btn_antar.addActionListener(buttonListener);
        btn_bayar.addActionListener(buttonListener);
        btn_login.addActionListener(buttonListener);
        btn_Hitung.addActionListener(buttonListener);
    }
    
    public void addListSelectionListener(ListSelectionListener listSelectionListener) {
        list_noMeja_koki.addListSelectionListener(listSelectionListener);
    }
    
    public void displayLaporan() {
        this.setLoginNama("");
        this.setLoginPassEmpty();
        laporanResto.show();
        laporanResto.pack();
        laporanResto.setLocationRelativeTo(null);
        laporanResto.setTitle("Laporan Bulan Ini");
    }
    
    public void displayGagalLogin() {
        loginGagal.show();
        loginGagal.pack();
        loginGagal.setLocationRelativeTo(this);
        loginGagal.setTitle("Login Gagal");
    }
    
    public void displayListPesanan(ArrayList<String> orders) {        
        DefaultListModel<String> listOrder = new DefaultListModel<>();
        for(String s: orders) {
            listOrder.addElement(s);
        }
        list_pemesanan.setModel(listOrder);
    }
    
    public void displayListPembayaran(ArrayList<String> orders) {        
        DefaultListModel<String> listOrder = new DefaultListModel<>();
        for(String s: orders) {
            listOrder.addElement(s);
        }
        list_pembayaran.setModel(listOrder);
    }
    
    public void displayListMejaKoki(ArrayList<String> masak) {
        DefaultListModel<String> listMasak = new DefaultListModel<>();
        for(String s: masak) {
            listMasak.addElement(s);
        }
        list_noMeja_koki.setModel(listMasak);
    }
    
    public void displayListPesananKoki(ArrayList<String> pesananKoki) {
        DefaultListModel<String> listMasak = new DefaultListModel<>();
        for(String s: pesananKoki) {
            listMasak.addElement(s);
        }
        list_otwMasak.setModel(listMasak);
    }
    
    public void enableBtnHapus(boolean b) {
        btn_hapus.setEnabled(b);
    }
       
}
